<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Calender" nsURI="https://tu-bs.de/isf/vacation_test" nsPrefix="calender">
  <eClassifiers xsi:type="ecore:EClass" name="Calender">
    <eOperations name="showGui"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dates" upperBound="-1"
        eType="#//Date" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="years" upperBound="-1"
        eType="#//Year" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kws" upperBound="-1" eType="#//KW"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dayType" lowerBound="1"
        eType="#//WorkingDayType" defaultValueLiteral="WorkingDay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holidayapplications" upperBound="-1"
        eType="#//HolidayApplication" containment="true" eOpposite="#//HolidayApplication/dates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekday" eType="#//WeekDay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leaveDays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkingDayType">
    <eLiterals name="WorkingDay"/>
    <eLiterals name="RestrictedDay" value="1"/>
    <eLiterals name="PublicHolyday" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HolidayApplication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAccepted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dates" eType="#//Date"
        eOpposite="#//Date/holidayapplications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" eType="#//Employee"
        eOpposite="#//Employee/holidayapplications"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponsiblePerson" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="standin" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//ResponsiblePerson"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holidayapplications" upperBound="-1"
        eType="#//HolidayApplication" eOpposite="#//HolidayApplication/employee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Year">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="months" upperBound="-1"
        eType="#//Month" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KW">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weekdates" upperBound="-1"
        eType="#//Date"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Month">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kws" upperBound="-1" eType="#//KW"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthname" eType="#//MonthName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDay">
    <eLiterals name="Monday"/>
    <eLiterals name="Tuesday" value="1"/>
    <eLiterals name="Wednesday" value="2"/>
    <eLiterals name="Thursday" value="3"/>
    <eLiterals name="Friday" value="4"/>
    <eLiterals name="Saturday" value="5"/>
    <eLiterals name="Sunday" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MonthName">
    <eLiterals name="January"/>
    <eLiterals name="February" value="1"/>
    <eLiterals name="March" value="2"/>
    <eLiterals name="April" value="3"/>
    <eLiterals name="May" value="4"/>
    <eLiterals name="June" value="5"/>
    <eLiterals name="July" value="6"/>
    <eLiterals name="August" value="7"/>
    <eLiterals name="September" value="8"/>
    <eLiterals name="October" value="9"/>
    <eLiterals name="November" value="10"/>
    <eLiterals name="December" value="11"/>
  </eClassifiers>
</ecore:EPackage>
