<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Calender" nsURI="https://tu-bs.de/isf/vacation_test" nsPrefix="calender">
  <eClassifiers xsi:type="ecore:EClass" name="Calender">
    <eOperations name="showGui"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dates" upperBound="-1"
        eType="#//Date" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="months" upperBound="-1"
        eType="#//Month" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Date">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/dates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dayType" lowerBound="1"
        eType="#//WorkingDayType" defaultValueLiteral="WorkingDay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holidayapplications" eType="#//HolidayApplication"
        eOpposite="#//HolidayApplication/dates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dates" upperBound="-1"
        eType="#//Date" eOpposite="#//Date/persons"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leaveDays" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkingDayType">
    <eLiterals name="WorkingDay"/>
    <eLiterals name="RestrictedDay" value="1"/>
    <eLiterals name="PublicHolyday" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HolidayApplication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAccepted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dates" eType="#//Date"
        eOpposite="#//Date/holidayapplications"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponsiblePerson" eSuperTypes="#//Person">
    <eOperations name="acceptApplication"/>
    <eOperations name="declineApplication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" eSuperTypes="#//Person">
    <eOperations name="createApplication"/>
    <eOperations name="sendApplication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="standin" eType="#//Employee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//ResponsiblePerson"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holidayapplications" upperBound="-1"
        eType="#//HolidayApplication" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Month">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weeks" upperBound="-1"
        eType="#//Week" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Week">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="day" upperBound="-1" eType="#//Day"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Day">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
